version: "2"
services:
 web:
  depends_on:
   - db
  image: "herkit/whereis"
  ports:
   - "3001:3001"
   - "10001-10004:10001-10004"
  env_file:
   - "prod.env"
   - "mysql.env"
  entrypoint: 
   - node
   - src/index.js
  links:
   - "db:db"
  restart: always

 db:
  image: "mysql"
  env_file:
   - "db.env"
   - "mysql.env"
  volumes:
   - "./data/mysql:/var/lib/mysql"